# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubekumber < Formula
  desc ""
  homepage "https://github.com/MatanyaLoewenthal/homebrew-tools"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MatanyaLoewenthal/kubekumber/releases/download/v0.0.4/kubekumber_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "9faf1581dbc5c18ca31adc00ad711dcb525f1d81c17d8ff81cdaf580753bcfa5"

      def install
        bin.install "kubekumber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MatanyaLoewenthal/kubekumber/releases/download/v0.0.4/kubekumber_0.0.4_Darwin_arm64.tar.gz"
      sha256 "b72f77433b814cc354454a5682b0a12e01cd6abcdeaa4ea16d141773a7479eea"

      def install
        bin.install "kubekumber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatanyaLoewenthal/kubekumber/releases/download/v0.0.4/kubekumber_0.0.4_Linux_arm64.tar.gz"
      sha256 "8b9131576cfa00b78303bc91da38af2c79194018e73cdb77d2073037fe74ce91"

      def install
        bin.install "kubekumber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MatanyaLoewenthal/kubekumber/releases/download/v0.0.4/kubekumber_0.0.4_Linux_x86_64.tar.gz"
      sha256 "9d478ffdcb04e9c8438c70afe499dde26227404d36955ce86c1734cfc0d2ff12"

      def install
        bin.install "kubekumber"
      end
    end
  end
end
